/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLQueryReaction.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   reaction/v1
// Description:
//   Rogag API for Commenting, UpVoting and DownVoting Funny Posts
// Classes:
//   GTLQueryReaction (3 custom class methods, 1 custom properties)

#import "GTLQueryReaction.h"

#import "GTLReactionCommentCreateRequest.h"
#import "GTLReactionCommentCreateResponse.h"
#import "GTLReactionCommentListRequest.h"
#import "GTLReactionCommentListResponse.h"
#import "GTLReactionVoteRequest.h"
#import "GTLReactionVoteResponse.h"

@implementation GTLQueryReaction

@dynamic fields;

#pragma mark -
#pragma mark "comment" methods
// These create a GTLQueryReaction object.

+ (id)queryForCommentCreateWithObject:(GTLReactionCommentCreateRequest *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"reaction.comment.create";
  GTLQueryReaction *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLReactionCommentCreateResponse class];
  return query;
}

+ (id)queryForCommentListWithObject:(GTLReactionCommentListRequest *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"reaction.comment.list";
  GTLQueryReaction *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLReactionCommentListResponse class];
  return query;
}

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryReaction object.

+ (id)queryForVoteWithObject:(GTLReactionVoteRequest *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"reaction.vote";
  GTLQueryReaction *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLReactionVoteResponse class];
  return query;
}

@end
