/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLQueryReaction.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   reaction/v1
// Description:
//   Rogag API for Commenting, UpVoting and DownVoting Funny Posts
// Classes:
//   GTLQueryReaction (3 custom class methods, 3 custom properties)

#import "GTLQueryReaction.h"

#import "GTLReactionApiCommentsCommentCreateRequest.h"
#import "GTLReactionApiCommentsCommentCreateResponse.h"
#import "GTLReactionApiCommentsCommentListResponse.h"
#import "GTLReactionApiCommentsVoteRequest.h"
#import "GTLReactionApiCommentsVoteResponse.h"

@implementation GTLQueryReaction

@dynamic cursor, fields, pageSize;

#pragma mark -
#pragma mark "comment" methods
// These create a GTLQueryReaction object.

+ (id)queryForCommentCreateWithObject:(GTLReactionApiCommentsCommentCreateRequest *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"reaction.comment.create";
  GTLQueryReaction *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLReactionApiCommentsCommentCreateResponse class];
  return query;
}

+ (id)queryForCommentList {
  NSString *methodName = @"reaction.comment.list";
  GTLQueryReaction *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLReactionApiCommentsCommentListResponse class];
  return query;
}

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryReaction object.

+ (id)queryForVoteWithObject:(GTLReactionApiCommentsVoteRequest *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"reaction.vote";
  GTLQueryReaction *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLReactionApiCommentsVoteResponse class];
  return query;
}

@end
