/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLQueryReaction.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   reaction/v1
// Description:
//   Rogag API for Commenting, UpVoting and DownVoting Funny Posts
// Classes:
//   GTLQueryReaction (3 custom class methods, 1 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLReactionCommentCreateRequest;
@class GTLReactionCommentListRequest;
@class GTLReactionVoteRequest;

@interface GTLQueryReaction : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (copy) NSString *fields;

#pragma mark -
#pragma mark "comment" methods
// These create a GTLQueryReaction object.

// Method: reaction.comment.create
//  Authorization scope(s):
//   kGTLAuthScopeReactionUserinfoEmail
// Fetches a GTLReactionCommentCreateResponse.
+ (id)queryForCommentCreateWithObject:(GTLReactionCommentCreateRequest *)object;

// Method: reaction.comment.list
//  Authorization scope(s):
//   kGTLAuthScopeReactionUserinfoEmail
// Fetches a GTLReactionCommentListResponse.
+ (id)queryForCommentListWithObject:(GTLReactionCommentListRequest *)object;

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryReaction object.

// Method: reaction.vote
//  Authorization scope(s):
//   kGTLAuthScopeReactionUserinfoEmail
// Fetches a GTLReactionVoteResponse.
+ (id)queryForVoteWithObject:(GTLReactionVoteRequest *)object;

@end
