/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLQueryReaction.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   reaction/v1
// Description:
//   Rogag API for Commenting, UpVoting and DownVoting Funny Posts
// Classes:
//   GTLQueryReaction (3 custom class methods, 3 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLReactionApiCommentsCommentCreateRequest;
@class GTLReactionApiCommentsVoteRequest;

@interface GTLQueryReaction : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (copy) NSString *cursor;
@property (assign) long long pageSize;

#pragma mark -
#pragma mark "comment" methods
// These create a GTLQueryReaction object.

// Method: reaction.comment.create
//  Authorization scope(s):
//   kGTLAuthScopeReactionUserinfoEmail
// Fetches a GTLReactionApiCommentsCommentCreateResponse.
+ (id)queryForCommentCreateWithObject:(GTLReactionApiCommentsCommentCreateRequest *)object;

// Method: reaction.comment.list
//  Optional:
//   cursor: NSString
//   pageSize: long long
//  Authorization scope(s):
//   kGTLAuthScopeReactionUserinfoEmail
// Fetches a GTLReactionApiCommentsCommentListResponse.
+ (id)queryForCommentList;

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryReaction object.

// Method: reaction.vote
//  Authorization scope(s):
//   kGTLAuthScopeReactionUserinfoEmail
// Fetches a GTLReactionApiCommentsVoteResponse.
+ (id)queryForVoteWithObject:(GTLReactionApiCommentsVoteRequest *)object;

@end
