/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLReaction_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   reaction/v1
// Description:
//   Rogag API for Commenting, UpVoting and DownVoting Funny Posts

#import "GTLReactionConstants.m"

#import "GTLReactionApiCommentsCommentCreateRequest.m"
#import "GTLReactionApiCommentsCommentCreateResponse.m"
#import "GTLReactionApiCommentsCommentListResponse.m"
#import "GTLReactionApiCommentsVoteRequest.m"
#import "GTLReactionApiCommentsVoteResponse.m"
#import "GTLReactionApiCommonUserAuthentication.m"

#import "GTLQueryReaction.m"
#import "GTLServiceReaction.m"
