/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLReactionCommentCreateRequest.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   reaction/v1
// Description:
//   Rogag API for Commenting, UpVoting and DownVoting Funny Posts
// Classes:
//   GTLReactionCommentCreateRequest (0 custom class methods, 4 custom properties)

#import "GTLReactionCommentCreateRequest.h"

#import "GTLReactionUserAuthentication.h"

// ----------------------------------------------------------------------------
//
//   GTLReactionCommentCreateRequest
//

@implementation GTLReactionCommentCreateRequest
@dynamic auth, isComment, message, postId;
@end
