/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLReactionCommentListResponse.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   reaction/v1
// Description:
//   Rogag API for Commenting, UpVoting and DownVoting Funny Posts
// Classes:
//   GTLReactionCommentListResponse (0 custom class methods, 2 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLReactionComments;

// ----------------------------------------------------------------------------
//
//   GTLReactionCommentListResponse
//

@interface GTLReactionCommentListResponse : GTLObject
@property (retain) NSArray *comments;  // of GTLReactionComments
@property (copy) NSString *cursor;
@end
