/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLReactionVoteResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   reaction/v1
// Description:
//   Rogag API for Commenting, UpVoting and DownVoting Funny Posts
// Classes:
//   GTLReactionVoteResponse (0 custom class methods, 6 custom properties)

#import "GTLReactionVoteResponse.h"

// ----------------------------------------------------------------------------
//
//   GTLReactionVoteResponse
//

@implementation GTLReactionVoteResponse
@dynamic commentCount, downvoteCount, isComment, pointsCount, postId,
         upvoteCount;
@end
