/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLReactionApiCommentsVoteResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   reaction/v1
// Description:
//   Rogag API for Commenting, UpVoting and DownVoting Funny Posts
// Classes:
//   GTLReactionApiCommentsVoteResponse (0 custom class methods, 1 custom properties)

#import "GTLReactionApiCommentsVoteResponse.h"

// ----------------------------------------------------------------------------
//
//   GTLReactionApiCommentsVoteResponse
//

@implementation GTLReactionApiCommentsVoteResponse
@dynamic isSuccessful;
@end
