/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLReactionApiCommentsCommentCreateRequest.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   reaction/v1
// Description:
//   Rogag API for Commenting, UpVoting and DownVoting Funny Posts
// Classes:
//   GTLReactionApiCommentsCommentCreateRequest (0 custom class methods, 3 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLReactionApiCommonUserAuthentication;

// ----------------------------------------------------------------------------
//
//   GTLReactionApiCommentsCommentCreateRequest
//

@interface GTLReactionApiCommentsCommentCreateRequest : GTLObject
@property (retain) GTLReactionApiCommonUserAuthentication *auth;
@property (copy) NSString *comment;
@property (copy) NSString *postId;
@end
