/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLReactionCommentCreateResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   reaction/v1
// Description:
//   Rogag API for Commenting, UpVoting and DownVoting Funny Posts
// Classes:
//   GTLReactionCommentCreateResponse (0 custom class methods, 0 custom properties)

#import "GTLReactionCommentCreateResponse.h"

// ----------------------------------------------------------------------------
//
//   GTLReactionCommentCreateResponse
//

@implementation GTLReactionCommentCreateResponse
@end
