/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLReactionCommentCreateResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   reaction/v1
// Description:
//   Rogag API for Commenting, UpVoting and DownVoting Funny Posts
// Classes:
//   GTLReactionCommentCreateResponse (0 custom class methods, 2 custom properties)

#import "GTLReactionCommentCreateResponse.h"

#import "GTLReactionAppError.h"

// ----------------------------------------------------------------------------
//
//   GTLReactionCommentCreateResponse
//

@implementation GTLReactionCommentCreateResponse
@dynamic appErrors, serverTime;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLReactionAppError class]
                                forKey:@"appErrors"];
  return map;
}

@end
