/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLReactionApiCommentsCommentCreateResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   reaction/v1
// Description:
//   Rogag API for Commenting, UpVoting and DownVoting Funny Posts
// Classes:
//   GTLReactionApiCommentsCommentCreateResponse (0 custom class methods, 1 custom properties)

#import "GTLReactionApiCommentsCommentCreateResponse.h"

// ----------------------------------------------------------------------------
//
//   GTLReactionApiCommentsCommentCreateResponse
//

@implementation GTLReactionApiCommentsCommentCreateResponse
@dynamic commentId;
@end
