/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLReactionComments.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   reaction/v1
// Description:
//   Rogag API for Commenting, UpVoting and DownVoting Funny Posts
// Classes:
//   GTLReactionComments (0 custom class methods, 1 custom properties)

#import "GTLReactionComments.h"

// ----------------------------------------------------------------------------
//
//   GTLReactionComments
//

@implementation GTLReactionComments
@dynamic comment;
@end
