/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLReactionConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   reaction/v1
// Description:
//   Rogag API for Commenting, UpVoting and DownVoting Funny Posts

#import "GTLReactionConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeReactionUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
