/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLReactionApiCommentsCommentCreateRequest.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   reaction/v1
// Description:
//   Rogag API for Commenting, UpVoting and DownVoting Funny Posts
// Classes:
//   GTLReactionApiCommentsCommentCreateRequest (0 custom class methods, 3 custom properties)

#import "GTLReactionApiCommentsCommentCreateRequest.h"

#import "GTLReactionApiCommonUserAuthentication.h"

// ----------------------------------------------------------------------------
//
//   GTLReactionApiCommentsCommentCreateRequest
//

@implementation GTLReactionApiCommentsCommentCreateRequest
@dynamic auth, comment, postId;
@end
