/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLReactionApiCommonUserAuthentication.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   reaction/v1
// Description:
//   Rogag API for Commenting, UpVoting and DownVoting Funny Posts
// Classes:
//   GTLReactionApiCommonUserAuthentication (0 custom class methods, 2 custom properties)

#import "GTLReactionApiCommonUserAuthentication.h"

// ----------------------------------------------------------------------------
//
//   GTLReactionApiCommonUserAuthentication
//

@implementation GTLReactionApiCommonUserAuthentication
@dynamic userId, userToken;
@end
