/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLReactionApiCommentsVoteRequest.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   reaction/v1
// Description:
//   Rogag API for Commenting, UpVoting and DownVoting Funny Posts
// Classes:
//   GTLReactionApiCommentsVoteRequest (0 custom class methods, 3 custom properties)

#import "GTLReactionApiCommentsVoteRequest.h"

#import "GTLReactionApiCommonUserAuthentication.h"

// ----------------------------------------------------------------------------
//
//   GTLReactionApiCommentsVoteRequest
//

@implementation GTLReactionApiCommentsVoteRequest
@dynamic auth, isUpVote, postId;
@end
