/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLServiceReaction.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   reaction/v1
// Description:
//   Rogag API for Commenting, UpVoting and DownVoting Funny Posts
// Classes:
//   GTLServiceReaction (0 custom class methods, 0 custom properties)

#import "GTLReaction.h"

@implementation GTLServiceReaction

#if DEBUG
// Method compiled in debug builds just to check that all the needed support
// classes are present at link time.
+ (NSArray *)checkClasses {
  NSArray *classes = [NSArray arrayWithObjects:
                      [GTLQueryReaction class],
                      [GTLReactionAppError class],
                      [GTLReactionCommentCreateRequest class],
                      [GTLReactionCommentCreateResponse class],
                      [GTLReactionCommentListRequest class],
                      [GTLReactionCommentListResponse class],
                      [GTLReactionComments class],
                      [GTLReactionUserAuthentication class],
                      [GTLReactionVoteRequest class],
                      [GTLReactionVoteResponse class],
                      nil];
  return classes;
}
#endif  // DEBUG

- (id)init {
  self = [super init];
  if (self) {
    // Version from discovery.
    self.apiVersion = @"v1";

    // From discovery.  Where to send JSON-RPC.
    // Turn off prettyPrint for this service to save bandwidth (especially on
    // mobile). The fetcher logging will pretty print.
    self.rpcURL = [NSURL URLWithString:@"https://rogag-server-stage.appspot.com/_ah/api/rpc?prettyPrint=false"];
  }
  return self;
}

@end
