/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLServiceUser.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   user/v1
// Description:
//   Rogag API for User Management
// Classes:
//   GTLServiceUser (0 custom class methods, 0 custom properties)

#import "GTLUser.h"

@implementation GTLServiceUser

#if DEBUG
// Method compiled in debug builds just to check that all the needed support
// classes are present at link time.
+ (NSArray *)checkClasses {
  NSArray *classes = [NSArray arrayWithObjects:
                      [GTLQueryUser class],
                      [GTLUserApiUserUserLoginRequest class],
                      [GTLUserApiUserUserLoginResponse class],
                      [GTLUserApiUserUserRegistrationRequest class],
                      [GTLUserApiUserUserRegistrationResponse class],
                      nil];
  return classes;
}
#endif  // DEBUG

- (id)init {
  self = [super init];
  if (self) {
    // Version from discovery.
    self.apiVersion = @"v1";

    // From discovery.  Where to send JSON-RPC.
    // Turn off prettyPrint for this service to save bandwidth (especially on
    // mobile). The fetcher logging will pretty print.
    self.rpcURL = [NSURL URLWithString:@"https://localhost:8080/_ah/api/rpc?prettyPrint=false"];
  }
  return self;
}

@end
