/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLUserLoginRequest.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   user/v1
// Description:
//   Rogag API for User Management
// Classes:
//   GTLUserLoginRequest (0 custom class methods, 9 custom properties)

#import "GTLUserLoginRequest.h"

// ----------------------------------------------------------------------------
//
//   GTLUserLoginRequest
//

@implementation GTLUserLoginRequest
@dynamic clientDevice, clientId, clientOS, clientOSVersion, clientVersion,
         clientVersionId, loginType, password, username;
@end
