/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLUserApiUserUserLoginResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   user/v1
// Description:
//   Rogag API for User Management
// Classes:
//   GTLUserApiUserUserLoginResponse (0 custom class methods, 4 custom properties)

#import "GTLUserApiUserUserLoginResponse.h"

// ----------------------------------------------------------------------------
//
//   GTLUserApiUserUserLoginResponse
//

@implementation GTLUserApiUserUserLoginResponse
@dynamic userId, userImageUrl, username, userToken;
@end
