/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLUserRegistrationResponse.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   user/v1
// Description:
//   Rogag API for User Management
// Classes:
//   GTLUserRegistrationResponse (0 custom class methods, 2 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLUserAppError;

// ----------------------------------------------------------------------------
//
//   GTLUserRegistrationResponse
//

@interface GTLUserRegistrationResponse : GTLObject
@property (retain) NSArray *appErrors;  // of GTLUserAppError
@property (copy) NSString *userId;
@end
