/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLUserLoginRequest.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   user/v1
// Description:
//   Rogag API for User Management
// Classes:
//   GTLUserLoginRequest (0 custom class methods, 9 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLUserLoginRequest
//

@interface GTLUserLoginRequest : GTLObject
@property (copy) NSString *clientDevice;
@property (copy) NSString *clientId;
@property (copy) NSString *clientOS;
@property (copy) NSString *clientOSVersion;
@property (copy) NSString *clientVersion;
@property (retain) NSNumber *clientVersionId;  // longLongValue
@property (copy) NSString *loginType;
@property (copy) NSString *password;
@property (copy) NSString *username;
@end
