/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLUserRegistrationResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   user/v1
// Description:
//   Rogag API for User Management
// Classes:
//   GTLUserRegistrationResponse (0 custom class methods, 3 custom properties)

#import "GTLUserRegistrationResponse.h"

#import "GTLUserAppError.h"

// ----------------------------------------------------------------------------
//
//   GTLUserRegistrationResponse
//

@implementation GTLUserRegistrationResponse
@dynamic appErrors, serverTime, userId;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLUserAppError class]
                                forKey:@"appErrors"];
  return map;
}

@end
