/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLUser.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   user/v1
// Description:
//   Rogag API for User Management

#import "GTLUserConstants.h"

#import "GTLUserApiUserUserLoginRequest.h"
#import "GTLUserApiUserUserLoginResponse.h"
#import "GTLUserApiUserUserRegistrationRequest.h"
#import "GTLUserApiUserUserRegistrationResponse.h"

#import "GTLQueryUser.h"
#import "GTLServiceUser.h"
