/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLUserApiUserUserRegistrationRequest.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   user/v1
// Description:
//   Rogag API for User Management
// Classes:
//   GTLUserApiUserUserRegistrationRequest (0 custom class methods, 3 custom properties)

#import "GTLUserApiUserUserRegistrationRequest.h"

// ----------------------------------------------------------------------------
//
//   GTLUserApiUserUserRegistrationRequest
//

@implementation GTLUserApiUserUserRegistrationRequest
@dynamic email, fullName, password;
@end
