/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLUserApiUserUserRegistrationResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   user/v1
// Description:
//   Rogag API for User Management
// Classes:
//   GTLUserApiUserUserRegistrationResponse (0 custom class methods, 1 custom properties)

#import "GTLUserApiUserUserRegistrationResponse.h"

// ----------------------------------------------------------------------------
//
//   GTLUserApiUserUserRegistrationResponse
//

@implementation GTLUserApiUserUserRegistrationResponse
@dynamic userId;
@end
