/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLUserApiUserUserRegistrationRequest.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   user/v1
// Description:
//   Rogag API for User Management
// Classes:
//   GTLUserApiUserUserRegistrationRequest (0 custom class methods, 3 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLUserApiUserUserRegistrationRequest
//

@interface GTLUserApiUserUserRegistrationRequest : GTLObject
@property (copy) NSString *email;
@property (copy) NSString *fullName;
@property (copy) NSString *password;
@end
