/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLUserConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   user/v1
// Description:
//   Rogag API for User Management

#import "GTLUserConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeUserUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
