/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLUserLoginResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   user/v1
// Description:
//   Rogag API for User Management
// Classes:
//   GTLUserLoginResponse (0 custom class methods, 6 custom properties)

#import "GTLUserLoginResponse.h"

#import "GTLUserAppError.h"

// ----------------------------------------------------------------------------
//
//   GTLUserLoginResponse
//

@implementation GTLUserLoginResponse
@dynamic appErrors, serverTime, userId, userImageUrl, username, userToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLUserAppError class]
                                forKey:@"appErrors"];
  return map;
}

@end
