/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLUserApiUserUserLoginRequest.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   user/v1
// Description:
//   Rogag API for User Management
// Classes:
//   GTLUserApiUserUserLoginRequest (0 custom class methods, 2 custom properties)

#import "GTLUserApiUserUserLoginRequest.h"

// ----------------------------------------------------------------------------
//
//   GTLUserApiUserUserLoginRequest
//

@implementation GTLUserApiUserUserLoginRequest
@dynamic password, username;
@end
