/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLUserRegistrationRequest.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   user/v1
// Description:
//   Rogag API for User Management
// Classes:
//   GTLUserRegistrationRequest (0 custom class methods, 4 custom properties)

#import "GTLUserRegistrationRequest.h"

// ----------------------------------------------------------------------------
//
//   GTLUserRegistrationRequest
//

@implementation GTLUserRegistrationRequest
@dynamic email, firstName, lastName, password;
@end
