/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLUserAppError.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   user/v1
// Description:
//   Rogag API for User Management
// Classes:
//   GTLUserAppError (0 custom class methods, 2 custom properties)

#import "GTLUserAppError.h"

// ----------------------------------------------------------------------------
//
//   GTLUserAppError
//

@implementation GTLUserAppError
@dynamic errorCode, errorMessage;
@end
