/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLUser_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   user/v1
// Description:
//   Rogag API for User Management

#import "GTLUserConstants.m"

#import "GTLUserApiUserUserLoginRequest.m"
#import "GTLUserApiUserUserLoginResponse.m"
#import "GTLUserApiUserUserRegistrationRequest.m"
#import "GTLUserApiUserUserRegistrationResponse.m"

#import "GTLQueryUser.m"
#import "GTLServiceUser.m"
