/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLImageGetUrlRequest.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   image/v1
// Description:
//   Rogag API for Images
// Classes:
//   GTLImageGetUrlRequest (0 custom class methods, 1 custom properties)

#import "GTLImageGetUrlRequest.h"

#import "GTLImageUserAuthentication.h"

// ----------------------------------------------------------------------------
//
//   GTLImageGetUrlRequest
//

@implementation GTLImageGetUrlRequest
@dynamic auth;
@end
