/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLImageAppError.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   image/v1
// Description:
//   Rogag API for Images
// Classes:
//   GTLImageAppError (0 custom class methods, 2 custom properties)

#import "GTLImageAppError.h"

// ----------------------------------------------------------------------------
//
//   GTLImageAppError
//

@implementation GTLImageAppError
@dynamic errorCode, errorMessage;
@end
