/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLImageGetUrlRequest.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   image/v1
// Description:
//   Rogag API for Images
// Classes:
//   GTLImageGetUrlRequest (0 custom class methods, 3 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLImageUserAuthentication;

// ----------------------------------------------------------------------------
//
//   GTLImageGetUrlRequest
//

@interface GTLImageGetUrlRequest : GTLObject
@property (retain) GTLImageUserAuthentication *auth;
@property (copy) NSString *fileName;
@property (copy) NSString *imageType;
@end
