/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLImageGetUrlResponse.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   image/v1
// Description:
//   Rogag API for Images
// Classes:
//   GTLImageGetUrlResponse (0 custom class methods, 3 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLImageAppError;

// ----------------------------------------------------------------------------
//
//   GTLImageGetUrlResponse
//

@interface GTLImageGetUrlResponse : GTLObject
@property (retain) NSArray *appErrors;  // of GTLImageAppError
@property (copy) NSString *downloadUrl;
@property (copy) NSString *uploadUrl;
@end
