/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLImageConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   image/v1
// Description:
//   Rogag API for Images

#import "GTLImageConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeImageUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
