application: rogag-server
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
# Endpoints handler
- url: /_ah/spi/.*
  script: ripoff9gag.api.APPLICATION

- url: /temp/images
  static_dir: temp/images

- url: /.*
  script: main.app

libraries:
- name: django
  version: latest

- name: pycrypto
  version: latest

- name: endpoints
  version: 1.0

- name: ssl
  version: latest
