/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLPostUserAuthentication.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   post/v1
// Description:
//   Rogag API for Viewing and Posting Funny Pics
// Classes:
//   GTLPostUserAuthentication (0 custom class methods, 2 custom properties)

#import "GTLPostUserAuthentication.h"

// ----------------------------------------------------------------------------
//
//   GTLPostUserAuthentication
//

@implementation GTLPostUserAuthentication
@dynamic userId, userToken;
@end
