/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLPostApiPostsUserPostListResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   post/v1
// Description:
//   Rogag API for Viewing and Posting Funny Pics
// Classes:
//   GTLPostApiPostsUserPostListResponse (0 custom class methods, 2 custom properties)

#import "GTLPostApiPostsUserPostListResponse.h"

#import "GTLPostApiCommonUserPost.h"

// ----------------------------------------------------------------------------
//
//   GTLPostApiPostsUserPostListResponse
//

@implementation GTLPostApiPostsUserPostListResponse
@dynamic cursor, posts;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLPostApiCommonUserPost class]
                                forKey:@"posts"];
  return map;
}

@end
