/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLPostConstants.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   post/v1
// Description:
//   Rogag API for Viewing and Posting Funny Pics

#import <Foundation/Foundation.h>

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLDefines.h"
#else
  #import "GTLDefines.h"
#endif

// Authorization scope
// View your email address
GTL_EXTERN NSString * const kGTLAuthScopePostUserinfoEmail;  // "https://www.googleapis.com/auth/userinfo.email"

// GTLQueryPost - Type
GTL_EXTERN NSString * const kGTLPostTypeHot;       // "HOT"
GTL_EXTERN NSString * const kGTLPostTypeTrending;  // "TRENDING"
