/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLPostConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   post/v1
// Description:
//   Rogag API for Viewing and Posting Funny Pics

#import "GTLPostConstants.h"

// Authorization scope
NSString * const kGTLAuthScopePostUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";

// GTLQueryPost - Type
NSString * const kGTLPostTypeHot      = @"HOT";
NSString * const kGTLPostTypeTrending = @"TRENDING";
