/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLPostUserAccount.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   post/v1
// Description:
//   Rogag API for Viewing and Posting Funny Pics
// Classes:
//   GTLPostUserAccount (0 custom class methods, 2 custom properties)

#import "GTLPostUserAccount.h"

// ----------------------------------------------------------------------------
//
//   GTLPostUserAccount
//

@implementation GTLPostUserAccount
@dynamic userId, username;
@end
