/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLPostUserPostCreateResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   post/v1
// Description:
//   Rogag API for Viewing and Posting Funny Pics
// Classes:
//   GTLPostUserPostCreateResponse (0 custom class methods, 1 custom properties)

#import "GTLPostUserPostCreateResponse.h"

// ----------------------------------------------------------------------------
//
//   GTLPostUserPostCreateResponse
//

@implementation GTLPostUserPostCreateResponse
@dynamic postId;
@end
