/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLPostApiPostsUserPostCreateResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   post/v1
// Description:
//   Rogag API for Viewing and Posting Funny Pics
// Classes:
//   GTLPostApiPostsUserPostCreateResponse (0 custom class methods, 1 custom properties)

#import "GTLPostApiPostsUserPostCreateResponse.h"

// ----------------------------------------------------------------------------
//
//   GTLPostApiPostsUserPostCreateResponse
//

@implementation GTLPostApiPostsUserPostCreateResponse
@dynamic postId;
@end
