/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLPostUserPostListResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   post/v1
// Description:
//   Rogag API for Viewing and Posting Funny Pics
// Classes:
//   GTLPostUserPostListResponse (0 custom class methods, 4 custom properties)

#import "GTLPostUserPostListResponse.h"

#import "GTLPostAppError.h"
#import "GTLPostUserPost.h"

// ----------------------------------------------------------------------------
//
//   GTLPostUserPostListResponse
//

@implementation GTLPostUserPostListResponse
@dynamic appErrors, cursor, posts, serverTime;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      [GTLPostAppError class], @"appErrors",
      [GTLPostUserPost class], @"posts",
      nil];
  return map;
}

@end
