/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLPostApiPostsUserPostCreateRequest.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   post/v1
// Description:
//   Rogag API for Viewing and Posting Funny Pics
// Classes:
//   GTLPostApiPostsUserPostCreateRequest (0 custom class methods, 4 custom properties)

#import "GTLPostApiPostsUserPostCreateRequest.h"

#import "GTLPostApiCommonUserAuthentication.h"

// ----------------------------------------------------------------------------
//
//   GTLPostApiPostsUserPostCreateRequest
//

@implementation GTLPostApiPostsUserPostCreateRequest
@dynamic auth, imageUrl, isUnsafe, title;
@end
