/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLPostApiCommonUserPost.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   post/v1
// Description:
//   Rogag API for Viewing and Posting Funny Pics
// Classes:
//   GTLPostApiCommonUserPost (0 custom class methods, 10 custom properties)

#import "GTLPostApiCommonUserPost.h"

#import "GTLPostApiCommonUserAccount.h"

// ----------------------------------------------------------------------------
//
//   GTLPostApiCommonUserPost
//

@implementation GTLPostApiCommonUserPost
@dynamic commentCount, downVoted, imageType, imageUrl, isUnsafe, owner, points,
         postId, title, upVoted;
@end
