/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLPostUserPostListRequest.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   post/v1
// Description:
//   Rogag API for Viewing and Posting Funny Pics
// Classes:
//   GTLPostUserPostListRequest (0 custom class methods, 3 custom properties)

#import "GTLPostUserPostListRequest.h"

// ----------------------------------------------------------------------------
//
//   GTLPostUserPostListRequest
//

@implementation GTLPostUserPostListRequest
@dynamic cursor, pageSize, type;
@end
