/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLPostApiCommonUserAccount.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   post/v1
// Description:
//   Rogag API for Viewing and Posting Funny Pics
// Classes:
//   GTLPostApiCommonUserAccount (0 custom class methods, 2 custom properties)

#import "GTLPostApiCommonUserAccount.h"

// ----------------------------------------------------------------------------
//
//   GTLPostApiCommonUserAccount
//

@implementation GTLPostApiCommonUserAccount
@dynamic userId, username;
@end
