/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLPostUserPost.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   post/v1
// Description:
//   Rogag API for Viewing and Posting Funny Pics
// Classes:
//   GTLPostUserPost (0 custom class methods, 10 custom properties)

#import "GTLPostUserPost.h"

#import "GTLPostUserAccount.h"

// ----------------------------------------------------------------------------
//
//   GTLPostUserPost
//

@implementation GTLPostUserPost
@dynamic commentCount, downVoted, imageType, imageUrl, isUnsafe, owner, points,
         postId, title, upVoted;
@end
