/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLPostUserPostCreateRequest.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   post/v1
// Description:
//   Rogag API for Viewing and Posting Funny Pics
// Classes:
//   GTLPostUserPostCreateRequest (0 custom class methods, 4 custom properties)

#import "GTLPostUserPostCreateRequest.h"

#import "GTLPostUserAuthentication.h"

// ----------------------------------------------------------------------------
//
//   GTLPostUserPostCreateRequest
//

@implementation GTLPostUserPostCreateRequest
@dynamic auth, imageUrl, isUnsafe, title;
@end
