/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLPost_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   post/v1
// Description:
//   Rogag API for Viewing and Posting Funny Pics

#import "GTLPostConstants.m"

#import "GTLPostApiCommonUserAccount.m"
#import "GTLPostApiCommonUserAuthentication.m"
#import "GTLPostApiCommonUserPost.m"
#import "GTLPostApiPostsUserPostCreateRequest.m"
#import "GTLPostApiPostsUserPostCreateResponse.m"
#import "GTLPostApiPostsUserPostListResponse.m"

#import "GTLQueryPost.m"
#import "GTLServicePost.m"
