/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLQueryPost.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   post/v1
// Description:
//   Rogag API for Viewing and Posting Funny Pics
// Classes:
//   GTLQueryPost (2 custom class methods, 1 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLPostUserPostCreateRequest;
@class GTLPostUserPostListRequest;

@interface GTLQueryPost : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (copy) NSString *fields;

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryPost object.

// Method: post.create
//  Authorization scope(s):
//   kGTLAuthScopePostUserinfoEmail
// Fetches a GTLPostUserPostCreateResponse.
+ (id)queryForCreateWithObject:(GTLPostUserPostCreateRequest *)object;

// Method: post.list
//  Authorization scope(s):
//   kGTLAuthScopePostUserinfoEmail
// Fetches a GTLPostUserPostListResponse.
+ (id)queryForListWithObject:(GTLPostUserPostListRequest *)object;

@end
