/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLQueryPost.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   post/v1
// Description:
//   Rogag API for Viewing and Posting Funny Pics
// Classes:
//   GTLQueryPost (2 custom class methods, 4 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLPostApiPostsUserPostCreateRequest;

@interface GTLQueryPost : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (copy) NSString *cursor;
@property (assign) long long pageSize;
@property (copy) NSString *type;

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryPost object.

// Method: post.create
//  Authorization scope(s):
//   kGTLAuthScopePostUserinfoEmail
// Fetches a GTLPostApiPostsUserPostCreateResponse.
+ (id)queryForCreateWithObject:(GTLPostApiPostsUserPostCreateRequest *)object;

// Method: post.list
//  Required:
//   type:
//      kGTLPostTypeHot: "HOT"
//      kGTLPostTypeTrending: "TRENDING"
//  Optional:
//   cursor: NSString
//   pageSize: long long
//  Authorization scope(s):
//   kGTLAuthScopePostUserinfoEmail
// Fetches a GTLPostApiPostsUserPostListResponse.
+ (id)queryForListWithType:(NSString *)type;

@end
