/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLQueryPost.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   post/v1
// Description:
//   Rogag API for Viewing and Posting Funny Pics
// Classes:
//   GTLQueryPost (2 custom class methods, 5 custom properties)

#import "GTLQueryPost.h"

#import "GTLPostUserPostCreateRequest.h"
#import "GTLPostUserPostCreateResponse.h"
#import "GTLPostUserPostListResponse.h"

@implementation GTLQueryPost

@dynamic cursor, fields, pageSize, sinceDate, type;

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryPost object.

+ (id)queryForCreateWithObject:(GTLPostUserPostCreateRequest *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"post.create";
  GTLQueryPost *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLPostUserPostCreateResponse class];
  return query;
}

+ (id)queryForListWithType:(NSString *)type {
  NSString *methodName = @"post.list";
  GTLQueryPost *query = [self queryWithMethodName:methodName];
  query.type = type;
  query.expectedObjectClass = [GTLPostUserPostListResponse class];
  return query;
}

@end
