/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLServicePost.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   post/v1
// Description:
//   Rogag API for Viewing and Posting Funny Pics
// Classes:
//   GTLServicePost (0 custom class methods, 0 custom properties)

#import "GTLPost.h"

@implementation GTLServicePost

#if DEBUG
// Method compiled in debug builds just to check that all the needed support
// classes are present at link time.
+ (NSArray *)checkClasses {
  NSArray *classes = [NSArray arrayWithObjects:
                      [GTLQueryPost class],
                      [GTLPostApiCommonUserAccount class],
                      [GTLPostApiCommonUserAuthentication class],
                      [GTLPostApiCommonUserPost class],
                      [GTLPostApiPostsUserPostCreateRequest class],
                      [GTLPostApiPostsUserPostCreateResponse class],
                      [GTLPostApiPostsUserPostListResponse class],
                      nil];
  return classes;
}
#endif  // DEBUG

- (id)init {
  self = [super init];
  if (self) {
    // Version from discovery.
    self.apiVersion = @"v1";

    // From discovery.  Where to send JSON-RPC.
    // Turn off prettyPrint for this service to save bandwidth (especially on
    // mobile). The fetcher logging will pretty print.
    self.rpcURL = [NSURL URLWithString:@"https://None/_ah/api/rpc?prettyPrint=false"];
  }
  return self;
}

@end
