/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLImageUserAuthentication.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   image/v1
// Description:
//   Rogag API for Images
// Classes:
//   GTLImageUserAuthentication (0 custom class methods, 2 custom properties)

#import "GTLImageUserAuthentication.h"

// ----------------------------------------------------------------------------
//
//   GTLImageUserAuthentication
//

@implementation GTLImageUserAuthentication
@dynamic userId, userToken;
@end
