/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLImage.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   image/v1
// Description:
//   Rogag API for Images

#import "GTLImageConstants.h"

#import "GTLImageAppError.h"
#import "GTLImageGetUrlRequest.h"
#import "GTLImageGetUrlResponse.h"
#import "GTLImageUserAuthentication.h"

#import "GTLQueryImage.h"
#import "GTLServiceImage.h"
